name: lint

on:
  workflow_dispatch:

  pull_request:
    paths-ignore:
      - '/.*'
      - '!.clang-format'
      - '**.adoc'
      - '**.md'

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DoozyX/clang-format-lint-action@v0.11
        with:
          source: '.'
          extensions: 'h,cpp,c'
          clangFormatVersion: 11
          inplace: True
      - uses: EndBug/add-and-commit@v4
        with:
          author_name: A robot on behalf of Maxim Samsonov
          author_email: m.samsonov@computer.org
          message: 'Committing clang-format changes'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ludeeus/action-shellcheck@master
